-#Diseñar un programa que solicite al operador un usuario y una contraseña,
 -#y que valide que esos datos sean correctos para permitir el ingreso al sistema.
 -usuario = input ("ingrese usuario: ")
 -contraseña = "nob"
 -if (usuario == "mauricio"):
 -    input ("ingrese contraseña: ")
 -    if (contraseña == "nob"):
 -        print ("ingreso correcto al sistema C-O-N-G-R-A-T-U-L-A-T-I-O-N-S")
 -else:
 -    print ("hasta la vista baby") 
